const menuButton=document.querySelector('.menu-toggle');
const nav=document.querySelector('.nav-links');
menuButton.addEventListener('click',()=>{const isOpen=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(isOpen));menuButton.textContent=isOpen?'✕':'☰'});
nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.textContent='☰'}));
const energyButton=document.querySelector('#energyButton');
energyButton.addEventListener('click',()=>{const mass=Number(document.querySelector('#massInput').value);const result=document.querySelector('#energyResult');if(!Number.isFinite(mass)||mass<0){result.textContent='Please enter a non-negative mass.';return}const energy=mass*299792458**2;result.innerHTML=`Energy released: <strong>${energy.toExponential(4)} joules</strong>`});
document.querySelector('#forceButton').addEventListener('click',()=>{const mass=Number(document.querySelector('#forceMass').value);const acceleration=Number(document.querySelector('#acceleration').value);const result=document.querySelector('#forceResult');if(!Number.isFinite(mass)||!Number.isFinite(acceleration)||mass<0){result.textContent='Please enter valid numbers (mass must be non-negative).';return}result.innerHTML=`Force: <strong>${(mass*acceleration).toLocaleString(undefined,{maximumFractionDigits:4})} newtons</strong>`});
const elements=[['H','Hydrogen',1,'nonmetal'],['He','Helium',2,'noble'],['Li','Lithium',3,'metal'],['Be','Beryllium',4,'metal'],['B','Boron',5,'nonmetal'],['C','Carbon',6,'nonmetal'],['N','Nitrogen',7,'nonmetal'],['O','Oxygen',8,'nonmetal'],['F','Fluorine',9,'nonmetal'],['Ne','Neon',10,'noble'],['Na','Sodium',11,'metal'],['Mg','Magnesium',12,'metal'],['Al','Aluminum',13,'metal'],['Si','Silicon',14,'nonmetal'],['P','Phosphorus',15,'nonmetal'],['S','Sulfur',16,'nonmetal'],['Cl','Chlorine',17,'nonmetal'],['Ar','Argon',18,'noble'],['K','Potassium',19,'metal'],['Ca','Calcium',20,'metal'],['Fe','Iron',26,'metal'],['Cu','Copper',29,'metal'],['Zn','Zinc',30,'metal'],['Br','Bromine',35,'nonmetal'],['Kr','Krypton',36,'noble'],['Ag','Silver',47,'metal'],['Sn','Tin',50,'metal'],['I','Iodine',53,'nonmetal'],['Xe','Xenon',54,'noble'],['Au','Gold',79,'metal'],['Hg','Mercury',80,'metal'],['Pb','Lead',82,'metal'],['Rn','Radon',86,'noble'],['U','Uranium',92,'metal']];
const periodicGrid=document.querySelector('#periodicGrid');
elements.forEach(([symbol,name,num,type])=>{const button=document.createElement('button');button.className=`element ${type}`;button.innerHTML=`<span class="atomic">${num}</span><b>${symbol}</b><small>${name}</small>`;button.setAttribute('aria-label',`${name}, atomic number ${num}`);button.addEventListener('click',()=>{document.querySelectorAll('.element.selected').forEach(el=>el.classList.remove('selected'));button.classList.add('selected');document.querySelector('#elementDetail').innerHTML=`<b style="color:#d5f56d">${name} (${symbol})</b> — atomic number ${num}. One of the essential ingredients in our cosmic story. <span>✳</span>`});periodicGrid.append(button)});
const canvas=document.querySelector('#mathCanvas');
const ctx=canvas.getContext('2d');
let selectedFunction='sin';
function fnValue(type,x){if(type==='sin')return Math.sin(x);if(type==='cos')return Math.cos(x);if(type==='square')return x*x/4;if(type==='cubic')return x*x*x/14;if(type==='exp')return Math.exp(x/2)-1;return Math.tan(x)}
function drawGraph(){const box=canvas.getBoundingClientRect();const dpr=window.devicePixelRatio||1;canvas.width=Math.max(1,Math.round(box.width*dpr));canvas.height=Math.max(1,Math.round(box.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);const w=box.width,h=box.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#edf0f7';ctx.lineWidth=1;for(let x=0;x<=w;x+=32){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<=h;y+=32){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const midY=h*.53,scaleX=w/12,scaleY=h*.29;ctx.strokeStyle='#adb8ce';ctx.lineWidth=1.2;ctx.beginPath();ctx.moveTo(0,midY);ctx.lineTo(w,midY);ctx.stroke();ctx.beginPath();ctx.moveTo(w/2,0);ctx.lineTo(w/2,h);ctx.stroke();ctx.strokeStyle='#335feb';ctx.lineWidth=3;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();let started=false;for(let px=0;px<=w;px+=1.5){const x=(px-w/2)/scaleX;let y=fnValue(selectedFunction,x);if(!Number.isFinite(y)||Math.abs(y)>4){started=false;continue}const py=midY-y*scaleY;if(!started){ctx.moveTo(px,py);started=true}else ctx.lineTo(px,py)}ctx.stroke()}
document.querySelectorAll('#functionButtons button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#functionButtons .selected').classList.remove('selected');button.classList.add('selected');selectedFunction=button.dataset.fn;document.querySelector('#graphName').textContent=`CURRENTLY PLOTTING: ${button.textContent}`;drawGraph()}));
new ResizeObserver(drawGraph).observe(canvas);
